[package]
name = "plonky2_rsa"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.97"
itertools = "0.14.0"
num = { version = "0.4.3", features = ["num-bigint"] }
num-bigint = "0.4.6"
plonky2 = { git = "https://github.com/0xPolygonZero/plonky2" }
plonky2_u32 = { git = "https://github.com/dgulotta/plonky2-u32.git" }
plonky2_gate_utils = { git = "https://github.com/dgulotta/plonky2-gate-utils.git" }
static_assertions = "1.1.0"
serde = "1.0.219"

[dev-dependencies]
rand = "0.8"
num-bigint = { version = "0.4.6", features = ["rand"] }
